version: '3'

services:
  my-react-app:
    image: "priy8808/dev-frontend:${bn}"
    container_name: my-react-app
    ports:
      - "3000:3000"
    environment:
      - bn=${BUILD_NUMBER}
    links:
      - my-db

  my-backend:
    image: "priy8808/dev-backend:${bn}"
    container_name: my-backend
    environment:
      - APP_ENV=test
      - bn=${BUILD_NUMBER}
    ports:
      - "4006:4006"
    links:
      - my-db

  my-db:
    image: "priy8808/dev-db:${bn}"
    container_name: dev-db
    ports:
      - "3306:3306"
    environment:
      - bn=${BUILD_NUMBE}
