version: '3'

services:
  uat-my-react-app:
    image: priy8808/uat-frontend:1
    container_name: my-react-app-uat
    ports:
      - "3001:3000"
    links:
      - uat-my-db
    restart: unless-stopped

  uat-my-backend:
    image: priy8808/uat-backend:1
    container_name: my-backend-uat
    environment:
      - APP_ENV=test
    ports:
      - "4007:4006"
    links:
      - uat-my-db
    restart: unless-stopped

  uat-my-db:
    image: priy8808/uat-db:1
    container_name: uat-db
    ports:
      - "3307:3306"
    restart: unless-stopped
