version: '3'

services:
  my-react-app:
    build: ./notes-ui
    image: priy8808/dev-frontend:v0
    ports:
      - "3000:3000"

  my-backend:
    build: ./server 
    image: priy8808/dev-backend:v0
    environment:
      - APP_ENV=test  
    ports:
      - "4006:4006"


  my-db:
      image: priy8808/dev-db:v0
      ports:
        - "3306:3306"
