version: '3'

services:
  my-react-app:
    image: priy8808/uat-frontend:v${BUILD_NUMBER}
    container_name: my-react-app-uat
    ports:
      - "3001:3000"
    links:
      - my-db

  my-backend:
    image: priy8808/uat-backend:v${BUILD_NUMBER}
    container_name: my-backend-uat
    environment:
      - APP_ENV=test
    ports:
      - "4007:4006"
    links:
      - my-db

  my-db:
    image: priy8808/uat-db:v${BUILD_NUMBER}
    container_name: uat-db
    ports:
      - "3307:3306"
