version: '3'

services:
  my-react-app:
    image: priy8808/prod-frontend:1
    container_name: my-react-app-prod
    ports:
      - "3002:3000"
    links:
      - my-db

  my-backend:
    image: priy8808/prod-backend:1
    container_name: my-backend-prod
    environment:
      - APP_ENV=test
    ports:
      - "4008:4006"
    links:
      - my-db

  my-db:
    image: priy8808/prod-db:1
    container_name: prod-db
    ports:
      - "3308:3306"
