version: '3'

services:
  my-react-app:
    image: priya8808/dev-frontend  # Use image without specifying a tag
    container_name: my-react-app
    ports:
      - "3000:3000"
    links:
      - my-db

  my-backend:
    image: priya8808/dev-backend  # Use image without specifying a tag
    container_name: my-backend
    environment:
      - APP_ENV=test
    ports:
      - "4006:4006"
    links:
      - my-db

  my-db:
    image: priya8808/dev-db  # Use image without specifying a tag
    container_name: dev-db
    ports:
      - "3306:3306"

