version: '3'

services:
  my-react-app:
    build: ./notes-ui
    image: priy8808/mine-repo:dev-frontend:v2
    ports:
      - "3000:3000"

  my-backend:
    build: ./server 
    image: priy8808/mine-repo:dev-backend:v2
    environment:
      - APP_ENV=test  
    ports:
      - "4006:4006"


  my-db:
      image: priy8808/mine-repo:dev-db:latest
      ports:
        - "3306:3306"
